### ISSUE TITLE
How to get the top-down map and the trajectory?

### ISSUE THREAD

**Issue by lizixiaoboluo** [18979705623/HSPR#1]
Hi, thanks for your great work.
Can you share how to get the top-down map and the corresponding trajectory?
thank you very much!

**Comment by XieZilongAI** [comment]
You can refer to the specification of [Matterport3D](https://github.com/niessner/Matterport/blob/master/data_organization.md) website  to download matterport_mesh file, Then install a software (e.g. meshlab) to load the file, remove the top and capture the aerial view. Navigation trajectory visualization reference [Matterport3DSimulator-web](https://github.com/peteanderson80/Matterport3DSimulator/tree/master/web).

**Comment by lizixiaoboluo** [comment]
thank you for your answer! 
Does the result file you generated include heading and elevation? I see that the val_unseen_shortest_agent.json file contains heading and elevation.

**Comment by XieZilongAI** [comment]
heading and elevation are not included. This is what they look like: {
"instr_id": "1648_185_0",
"predObjId": 185,
"trajectory": [......]
}, and it can also be visualized in Matterport3DSimulator-web.

**Comment by lizixiaoboluo** [comment]
Thank you very much for your help.
However, I still want to know how to draw the trajectories on the aerial view, which has been bothering me for a long time.
thank you very much!

**Comment by XieZilongAI** [comment]
Thank you for your attention, and I'm sorry it took me so long to discover your problem. I am uncertain if there is a shortcut. I directly overlay the trajectories onto the bird's-eye view. After obtaining a JSON file of the navigation results, you can visualize them in the Matterport3D simulator and map the visualized trajectory to the corresponding location on the bird's-eye view. By carefully comparing the environment in the simulator with the bird's-eye view, you can determine the precise location of the trajectory on the bird's-eye view.

**Comment by 18979705623** [comment]
completed
